# Generated by Django 4.2.5 on 2023-09-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Creature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creatures.creature",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("value", models.IntegerField()),
                (
                    "allele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creatures.allele",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="allele",
            name="gene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="creatures.gene"
            ),
        ),
    ]
